---
- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest update_cache=yes

- name: Change default symfony4+ nginx site
  become: yes
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Change default symfony2 nginx site
  become: yes
  template: src=default-symfony2.tpl dest=/etc/nginx/sites-available/default-symfony2
  notify: restart nginx

- name: Update the vagrant user permissions
  become: yes
  shell: usermod -a -G www-data vagrant
